name: action-lab

on:
  [push, pull_request]

jobs:
  job0:
    runs-on: ubuntu-latest
    name: job0
    steps:
      - uses: vacabun/action-demo@main
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
  pkgs-test:
    uses: vacabun/action-demo/.github/workflows/main.yml@main
    
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir public
          echo "<!DOCTYPE html><html><head><title>HTML Page</title></head><body><h1>Hello, World!</h1></body></html>" > public/index.html
      # 将 public 目录下生成的静态网站文件上传到 gh-pages 分支
      - uses: jamesives/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: public
          
          
    
