name: action-lab

on:
  [push, pull_request]

jobs:
  job0:
    runs-on: ubuntu-latest
    name: job0
    steps:
      - uses: vacabun/action-demo@main
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
  action-demo:
    uses: vacabun/action-demo/.github/workflows/main.yml@main
    with:
      list: |-
        input_1
        input_2
 
          
          
    
