name: action-lab

on:
  [push, pull_request]

jobs:
  job0:
    runs-on: ubuntu-latest
    name: job0
    steps:
      - uses: vacabun/action-demo@main
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
  pkgs-test:
    uses: vacabun/action-demo/.github/workflows/main.yml@main
 
          
          
    
