name: action-lab

on:
  [push, pull_request]

jobs:
  job0:
    runs-on: ubuntu-latest
    name: job0
    steps:
      - uses: vacabun/action-demo@main
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
  action-demo:
    uses: vacabun/action-demo/.github/workflows/main.yml@main
    with:
      list: |-
        input_1
        input_2
  pkgs-test:
    uses: vacabun/pkgs-test/.github/workflows/pkgs-action.yml@feature_input_pkgs_list
    with:
        package-append-res: false
        deploy-pages: false
        pkgs-test-repository: vacabun/pkgs-test
        pkgs-test-branch: feature_input_pkgs_list
        test-specific-pkgs: true
        pkgs: |
          hello
          LiteOS-SDK
 
          
          
    
