name: Check Spelling

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "**"
  pull_request_target:
    branches:
    - "**"
    types:
    - 'opened'
    - 'reopened'
    - 'synchronize'

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      actions: read
      security-events: write
    steps:
    - uses: actions/checkout@v4.0.0

    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@main
      with:
        only_check_changed_files: 1
        extra_dictionaries:
          cspell:software-terms/dict/softwareTerms.txt
